disabled gpg signing

diff --git a/.github/workflows/update-collection.yml b/.github/workflows/update-collection.yml
--- a/.github/workflows/update-collection.yml
+++ b/.github/workflows/update-collection.yml
@@ -26,29 +26,12 @@ jobs:
         run: |
           mkdir -p tools
           node --version
-          node tools/update-collection.mjs || { echo "Generator failed"; exit 1; }
-
-      - name: Configure GPG
-        run: |
-          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
-          echo "use-agent" > ~/.gnupg/gpg.conf
-          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
-          echo "default-cache-ttl 34560000" > ~/.gnupg/gpg-agent.conf
-          echo "max-cache-ttl 34560000" >> ~/.gnupg/gpg-agent.conf
-          gpgconf --kill gpg-agent
-          export GPG_TTY=$(tty)
+          node tools/update-collection.mjs || { echo "generator failed"; exit 1; }
 
       - name: Commit Changes
-        env:
-          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
-          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "2219168+danydodson@users.noreply.github.com"
-          git config commit.gpgSign true
-          git config user.signingkey $GPG_KEY_ID
-          echo "$GPG_PASSPHRASE" | gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 --status-fd 1 --sign-key $GPG_KEY_ID
           git add readme.md
           git diff --cached --quiet && echo "no changes" || git commit -m "chore: auto-update script collection"
           git push
-
